site_name: GloboDocs - Portal de DocumentaÃ§Ã£o de Procedimentos Globo Pharma
site_description: Portal de DocumentaÃ§Ã£o do projeto GloboDocs

theme:
  name: material
  logo: assets/LogoLaranja.png
  favicon: assets/favicon.png

  icon:
    repo: fontawesome/brands/github

  language: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

repo_url: https://github.com/GloboPharma/GloboDocs
repo_name: GloboPharma/GloboDocs

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Guia de InÃ­cio: guia.md
  - ðŸ§ª Qualidade:
      - Normas e POPs: qualidade/normas.md
  - ðŸ“¦ OperaÃ§Ãµes:
      - Fluxo de Trabalho: operacoes/fluxo.md
  - ðŸ’» Tecnologia:
      - ConfiguraÃ§Ãµes: ti/configuracao.md
  - ðŸ‘¥ RH:
      - IntegraÃ§Ã£o: rh/index.md # Lembre de criar este arquivo
