site_name: GloboDocs - Portal de Documenta√ß√£o de Procedimentos Globo Pharma
site_description: Portal de Documenta√ß√£o do projeto GloboDocs

theme:
  name: material
  logo: assets/LogoLaranja.png
  favicon: assets/favicon.png
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.tabs.link

repo_url: https://github.com/GloboPharma/GloboDocs
repo_name: GloboPharma/GloboDocs

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md

  - üß≠ Governan√ßa:
      - Escopo: governanca/escopo.md
      - Matriz RACI: governanca/raci.md
      - Gest√£o de Mudan√ßas: governanca/change.md
      - GAP Analysis: governanca/gap-analysis.md
      - Templates:
          - Infraestrutura:
              - Modelo Procedimento Infra: governanca/templates/infraestrutura/modelo-procedimento-infraestrutura.md
              - Modelo Configura√ß√£o Infra: governanca/templates/infraestrutura/modelo-configuracao-infraestrutura.md
          - Sistemas:
              - Modelo Procedimento Sistemas: governanca/templates/sistemas/modelo-procedimento-sistemas.md
              - Modelo Configura√ß√£o Sistemas: governanca/templates/sistemas/modelo-configuracao-sistemas.md
  - üè≠ Produ√ß√£o:
      - Fluxo de Trabalho: producao/fluxo.md
      - Procedimentos: producao/procedimentos.md
  - üíª Tecnologia (TI):
      - Infraestrutura:
          - Procedimentos:
              - Firewall: ti/infraestrutura/procedimentos/firewall.md
              - Servidores: ti/infraestrutura/procedimentos/servidores.md
              - Telefonia: ti/infraestrutura/procedimentos/telefonia.md
          - Configura√ß√µes:
              - Firewall: ti/infraestrutura/configuracoes/firewall.md
              - Servidores: ti/infraestrutura/configuracoes/servidores.md
              - Telefonia: ti/infraestrutura/configuracoes/telefonia.md
      - Sistemas:
          - Procedimentos:
              - SAP: ti/sistemas/procedimentos/sap.md
              - BEAS: ti/sistemas/procedimentos/beas.md
              - WMS: ti/sistemas/procedimentos/wms.md
              - SESUITE: ti/sistemas/procedimentos/sesuite.md
              - GLPI: ti/sistemas/procedimentos/glpi.md
              - SURICATO: ti/sistemas/procedimentos/suricato.md
              - STARSOFT: ti/sistemas/procedimentos/starsoft.md
              - COGTIVE: ti/sistemas/procedimentos/cogtive.md
          - Configura√ß√µes:
              - SAP: ti/sistemas/configuracoes/sap.md
              - BEAS: ti/sistemas/configuracoes/beas.md
              - WMS: ti/sistemas/configuracoes/wms.md
              - SESUITE: ti/sistemas/configuracoes/sesuite.md
              - GLPI: ti/sistemas/configuracoes/glpi.md
              - SURICATO: ti/sistemas/configuracoes/suricato.md
              - STARSOFT: ti/sistemas/configuracoes/starsoft.md
              - COGTIVE: ti/sistemas/configuracoes/cogtive.md
  - üõ°Ô∏è Garantia da Qualidade:
      - Normas: garantia/normas.md
      - Procedimentos: garantia/procedimentos.md

  - üë• Gente e Gest√£o:
      - Normas: gentegestao/normas.md
      - Procedimentos: gentegestao/procedimentos.md

  - üí∞ Financeiro:
      - Normas: financeiro/normas.md
      - Procedimentos: financeiro/procedimentos.md

  - ‚öñÔ∏è Fiscal:
      - Normas: fiscal/normas.md
      - Procedimentos: fiscal/procedimentos.md

  - ü§ù Comercial:
      - Normas: comercial/normas.md
      - Procedimentos: comercial/procedimentos.md
